name: Playwright Tests
on:
  # push:
  #   branches: [ main, master ]
  # pull_request:
  #   branches: [ main, master ]
  repository_dispatch:
    types: [run-playwright-test]
  workflow_dispatch:
    inputs:
      project:
        description: 'Run test on project:'
        required: true
        type: choice
        options:
          - library
          - 3wschools
          - hoist
      environment:
        description: 'Run test on environment:'
        required: true
        type: choice
        options:
          - dev
          - stage
          - uat
      tags:
        description: 'Test scenario tags'
        required: false
        type: boolean
      
jobs:
  pr-review:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'pull_request'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 
  manual-run:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: ENV=${{ github.event.inputs.environment }} npx playwright test ./projects/${{ github.event.inputs.project }}/tests/noLogin.test.ts --project=chromium
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30
  new-deploy-test:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    if: github.event_name == 'repository_dispatch' && github.event.action == 'run-playwright-test'
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-node@v4
      with:
        node-version: lts/*
    - name: Install dependencies
      run: npm ci
    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
    - name: Run Playwright tests
      run: npx playwright test --project=chromium
      env:
        CI_BASE_URL: ${{ github.event.client_payload.app_url }}
    - uses: actions/upload-artifact@v4
      if: always()
      with:
        name: playwright-report
        path: playwright-report/
        retention-days: 30 
     
